language: go

go:
  - 1.12

install:
  - echo "Skip go get"

before_script:
  - "sudo cat /etc/docker/daemon.json | jq '. + {\"insecure-registries\": [\"172.30.0.0/16\"]}' | sudo tee /etc/docker/daemon.json"
  - sudo systemctl restart docker
  - sudo docker run -d -p 5000:5000 --restart=always --name registry registry:2
  - sudo ps aux | grep docker

script:
  - go build .
  - go test -timeout 60s .
  - travis_wait 40 test/e2e.sh clusterup

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: true
